version: '3.8'

services:
  db-init:
    build:
      context: .
      target: db-init
    environment:
      - DB_USER=${DB_USER:-twilio_user}
      - DB_PASSWORD=${DB_PASSWORD:-your_password}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-lendingkart_db}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  app:
    build:
      context: .
      target: app
    environment:
      - DB_USER=${DB_USER:-twilio_user}
      - DB_PASSWORD=${DB_PASSWORD:-your_password}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-lendingkart_db}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - PHONE_NUMBER_FROM=${PHONE_NUMBER_FROM}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DOMAIN=${DOMAIN}
      - SENDER_PASSWORD=${SENDER_PASSWORD}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - HUMAN_AGENT_NUMBER=${HUMAN_AGENT_NUMBER}
    ports:
      - "5050:5050"
    depends_on:
      - db-init
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
      - MYSQL_DATABASE=${DB_NAME:-lendingkart_db}
      - MYSQL_USER=${DB_USER:-twilio_user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-your_password}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root_password}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge 